version: '3'

services:
  # optional dictionary server (add other dictionaries via Dockerfile)
  # comment it out if you don't need it

  dict:
    image: cthulhoo/the-epube-dict
    restart: unless-stopped

  app:
    image: cthulhoo/the-epube-fpm-pgsql-static
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app:/var/www/html
      - ${BOOKS_DIR}:/books:ro

  web-nginx:
    image: cthulhoo/the-epube-web-nginx
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - app

volumes:
  app:

